env:
  global:
    - CC_TEST_REPORTER_ID=4a566ce816b1d74aca5bb52fcb2c27240215ff5e03a51d64830602257d8962a6
language: node_js
node_js:
  - "node"
  - "7"
before_script:
  - npm run lint
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
cache:
  directories:
    - "node_modules"
